version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.10"
  type_checker = "mypy"
  max_line_length = 88
  skip_doc_coverage = ["tests"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"
enabled = true